# Generated by Django 2.1.1 on 2019-07-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudcsv', '0010_auto_20190731_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
