# Generated by Django 2.1.1 on 2019-07-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_realtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='realtor',
        ),
    ]
