# Generated by Django 2.1.1 on 2019-08-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190801_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_main',
            new_name='photo_main_one',
        ),
    ]
