# Generated by Django 2.1.1 on 2019-08-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icontent', '0004_auto_20190630_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='logo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
