# Generated by Django 2.1.1 on 2019-06-27 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_email', models.CharField(max_length=30)),
                ('header_phone', models.CharField(max_length=20)),
                ('bottom_content_one', models.CharField(max_length=200)),
                ('bottom_content_two', models.CharField(max_length=200)),
                ('bottom_content_three', models.CharField(max_length=200)),
                ('footer_facebook', models.CharField(max_length=200)),
                ('footer_twitter', models.CharField(max_length=200)),
                ('footer_instragram', models.CharField(max_length=200)),
                ('footer_linkedin', models.CharField(max_length=200)),
                ('footer_pinterest', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
