# Generated by Django 2.1.1 on 2019-07-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
