# Generated by Django 2.1.1 on 2019-07-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudcsv', '0004_auto_20190729_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='images',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
