# Generated by Django 2.1.1 on 2019-07-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudcsv', '0008_auto_20190730_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='images',
            field=models.ImageField(default=1, upload_to='photos'),
            preserve_default=False,
        ),
    ]
