# Generated by Django 2.1.1 on 2019-08-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudcsv', '0011_auto_20190731_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
