# Generated by Django 2.1.1 on 2019-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190704_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.ImageField(blank=True, null=True, upload_to='books/pdfs/'),
        ),
    ]
