# Generated by Django 2.1.1 on 2019-06-30 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profileband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(blank=True, max_length=200)),
                ('name_one', models.CharField(blank=True, max_length=200)),
                ('summary_text_one', models.TextField(blank=True, max_length=2000, null=True)),
                ('profile_facebook_one', models.CharField(blank=True, max_length=200)),
                ('profile_twitter_one', models.CharField(blank=True, max_length=200)),
                ('profile_instragram_one', models.CharField(blank=True, max_length=200)),
                ('profile_linkedin_one', models.CharField(blank=True, max_length=200)),
                ('profile_photo_one', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
